name: Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365 # v2

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ vars.PROMISE_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROMISE_DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          push: true
          tags: promisesolutions/blurple-hammer:latest
