name: Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

    - name: Touch .env file
      run: echo -e "APPEALS_PORT=1234\nSTAFF_PORTAL_PORT=2345" > .env

    - name: Test docker compose build
      run: docker compose build
