name: Docker Compose

on:
  push:
  pull_request:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}