name: Label sync

on:
  push:
    branches:
      - main
    paths:
      - './github/labels.yml'
  workflow_dispatch:

jobs:
  label-sync:
    name: Sync labels with labels.yml
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Label sync
      uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
