name: Label sync

on:
  push:
    branches:
      - main
    paths:
      - './github/labels.yml'
  workflow_dispatch:

jobs:
  label-sync:
    name: Sync labels with labels.yml
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Label sync
      uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
